---
title: 'Santa Cruz Creek Calibration'
author: ''
date: '2020-01-09'
slug: arcswat_monthly
categories: []
tags:
 - analysis
 - water
subtitle: ''
summary: 'ArcSWAT simulated and Santa Cruz Creek historical discharge calibration.'
authors: []
lastmod: '2020-01-09T15:02:28-08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}

library(tidyverse)
library(readxl)
library(janitor)
library(ggthemes)
library(here)
library(ggplot2)
library(gridExtra)

```

Santa Cruz Creek USGS gauge flows into Cachuma 
```{r}
#Read in flow data 
sc_usgs_flow <- read.csv("sc_creek_clean.csv")

sc_usgs_flow$dis_cfs <- as.numeric(as.character(sc_usgs_flow$dis_cfs))
#creat cloumn for daily inflow in cumecs (cfs to cubic meters per second (cumecs)) 
sc_usgs_flow <- sc_usgs_flow %>% 
  mutate(dis_cumecs = (dis_cfs*0.03)) 

sc_usgs_flow$date <- as.Date(sc_usgs_flow$date, "%m/%d/%Y")
sc_usgs_flow$month_yr <- format(as.Date(sc_usgs_flow$date), "%Y-%m")

sc_usgs_flow_month <- sc_usgs_flow %>% 
  group_by(month_yr) %>% 
  mutate(usgs_month_flow = sum(dis_cumecs)) %>% 
  mutate(usgs_month_flow_cfs = sum(dis_cfs)) #Now aggregating CFS by month for report 


```

Santa Cruz Creek Plot
```{r}

sc_usgs_month_plot <-ggplot(sc_usgs_flow_month, aes(x = date, y = usgs_month_flow)) +
  geom_point(color = "dark blue") +
  geom_line(color = "dark blue") +
  theme_classic() +
  ggtitle("Monthly Flow Santa Cruz Creek at USGS Santa Cruz Creek (1980 - 2018)") +
  xlab("Date") +
  ylab("Total Monthly Inflow (cumecs)") +
  theme(plot.title = element_text(size=12))

sc_usgs_month_plot

```

ArcSWAT Calibrations
```{r}
#### 4 STATION FLOW CACHUMA CN 30, CH K2 100, AND SOL AWC +0.20 AND ESCO 50
sy_sub4_swat_cach_cn30_k100_awc2 <- read_xlsx("daily_cachuma_final_calibration_rch.xlsx") %>% 
  clean_names() %>% 
  filter(sub == 4) %>%
  select(year, mon, flow_ou_tcms) %>% 
  add_column(date = NA) %>% 
  mutate(date = seq(from = as.Date("1983-01-01"), to = as.Date("2018-12-31"), by = 'day')) %>% # Add date column
  add_column(month_yr = NA)

sy_sub4_swat_cach_cn30_k100_awc2$month_yr <- format(as.Date(sy_sub4_swat_cach_cn30_k100_awc2$date), "%Y-%m")

sy_sub4_swat_cach_cn30_k100_awc2 <- sy_sub4_swat_cach_cn30_k100_awc2 %>% 
  group_by(month_yr) %>% 
  mutate(month_flow = sum(flow_ou_tcms)) %>% 
  mutate(month_flow_cfs = sum(flow_ou_tcms*35.3))

```

ArcSWAT calibration Plot
```{r}

sy_sub4_cach_calib_plot <-ggplot(sy_sub4_swat_cach_cn30_k100_awc2, aes(x = date, y = month_flow)) +
  geom_point(color = "dark blue") +
  geom_line(color = "dark blue") +
  theme_classic() +
  ggtitle("Monthly Flow Sub-Basin 4 ArcSWAT (1980 - 2018)") +
  xlab("Date") +
  ylab("Total Monthly Inflow (cumecs)") +
  theme(plot.title = element_text(size=12))

sy_sub4_cach_calib_plot

```


```{r}
theme_black = function(base_size = 12, base_family = "") {
 
  theme_grey(base_size = base_size, base_family = base_family) %+replace%
 
    theme(
      # Specify axis options
      axis.line = element_blank(),  
      axis.text.x = element_text(size = base_size*0.8, color = "white", lineheight = 0),  
      axis.text.y = element_text(size = base_size*0.8, color = "white", lineheight = 0),  
      #axis.ticks = element_line(color = "white", size  =  0.2),  
      axis.title.x = element_text(size = base_size, color = "white", margin = margin(0, 10, 0, 0)),  
      axis.title.y = element_text(size = base_size, color = "white", angle = 90, margin = margin(0, 10, 0, 0)),  
      axis.ticks.length = unit(0.3, "lines"),   
      # Specify legend options
      legend.background = element_rect(color = NA, fill = "black"),  
      legend.key = element_rect(color = "white",  fill = "black"),  
      legend.key.size = unit(1.2, "lines"),  
      legend.key.height = NULL,  
      legend.key.width = NULL,      
      legend.text = element_text(size = base_size*0.8, color = "white"),  
      legend.title = element_text(size = base_size*0.8, face = "bold", hjust = 0, color = "white"),  
      legend.position = "bottom",  
      legend.text.align = NULL,  
      legend.title.align = NULL,  
      legend.direction = "horizontal",  
      legend.box = NULL, 
      # Specify panel options
      panel.background = element_rect(fill = "black", color  =  NA),  
      panel.border = element_rect(fill = NA, color = "white"),  
      panel.grid.major = element_line(color = "black"),  
      panel.grid.minor = element_line(color = "black"),  
      panel.margin = unit(0, "lines"),   
      # Specify facetting options
      strip.background = element_rect(fill = "grey30", color = "grey10"),  
      strip.text.x = element_text(size = base_size*0.8, color = "white"),  
      strip.text.y = element_text(size = base_size*0.8, color = "white",angle = -90),  
      # Specify plot options
      plot.background = element_rect(color = "black", fill = "black"),  
      plot.title = element_text(size = base_size*1.2, color = "white"),  
      plot.margin = unit(rep(1, 4), "lines")
 
    )
 
}
```



Compare Santa Cruz USGS gauge with ArcSWAT calibration attempt
```{r}

# Combining Sub4 SWAT CN 30 and Ch K2 100 and AWC +0.20 vs. USGS Santa Cruz
sc_flow_month_comp_CN <-ggplot() +
  #geom_point(aes(y = sy_sub4_swat_cach_cn30_k100_awc2$month_flow, x = sy_sub4_swat_cach_cn30_k100_awc2$date, color = "month_flow"), alpha = 0.4) +
  geom_line(aes(group =1, y = sy_sub4_swat_cach_cn30_k100_awc2$month_flow_cfs, x = sy_sub4_swat_cach_cn30_k100_awc2$date, color = "month_flow_cfs"), alpha = 0.6, size = 1) +
 # geom_point(aes(y = sc_usgs_flow_month$usgs_month_flow, x = sc_usgs_flow_month$date, color = "usgs_month_flow"), alpha = 0.4) +
  geom_line(aes(group=1, y = sc_usgs_flow_month$usgs_month_flow_cfs, x = sc_usgs_flow_month$date, color = "usgs_month_flow_cfs"), alpha = 0.6, size = 1) +
  theme_classic() +
  ggtitle("Observed USGS Flow Santa Cruz vs. \nArcSWAT Flow Sub-basin 4\n ") +
  xlab("Year") +
  ylab(bquote('Total Monthly Streamfow ('~ft^3/s~')')) + 
  theme(plot.title = element_text(size=12)) +
theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.title = element_text(size=10), legend.position = "bottom", legend.background = element_rect(fill="white",
                                  size=0.5, linetype="solid", 
                                  colour ="black")) +
  guides(color=guide_legend("Streamflow\n1980-2018")) +
  #scale_x_date(limits = as.Date(c("1998-01-01","2018-01-01"))) +
  #scale_y_continuous(limits = c(0,250)) +
  scale_color_manual(labels = c("Simulated", "Observed"), values = c("turquoise4", "firebrick1")) #+
  #theme_black()

plot(sc_flow_month_comp_CN)
```
